# BroadCasting

In [4]:
import numpy as np

In [5]:
M= np.ones((2,3))
M

array([[1., 1., 1.],
       [1., 1., 1.]])

In [6]:
a = np.arange(3)
a

array([0, 1, 2])

In [7]:
print(M)
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]
[0 1 2]


In [8]:
temp = M+a
temp

array([[1., 2., 3.],
       [1., 2., 3.]])

In [9]:
# Try Out 16

In [10]:
C= np.array([20,25,30,35])
F= np.array([68,77,86,95])

In [11]:
temp =  C*9/5+32

temp

array([68., 77., 86., 95.])

In [12]:
x = temp == F
print(x)
# if x:
#     print(True)
# else:
#     print(False)

[ True  True  True  True]


In [13]:
print(np.array_equal(temp,F))

True


# 18 Try Out 

In [14]:
# Create a 2D array with random values
student = np.random.randint(60,80,(6,4))
print(student)


[[78 68 72 73]
 [68 64 67 75]
 [62 63 73 75]
 [73 63 72 76]
 [69 65 64 70]
 [65 63 61 72]]


In [15]:
Avg1= np.mean(student, axis = 1)  #avg all
print(Avg1)

[72.75 68.5  68.25 71.   67.   65.25]


In [16]:
# 1st row

In [65]:
# 1st row
student[0,:]

array([83, 73, 77, 78])

In [18]:
# 1st row last column

In [19]:
student[0,3:]

array([73])

In [20]:
with_bonus = student[0,:]+5
print(with_bonus)

[83 73 77 78]


In [21]:
bonus = 5
student[0,:] += bonus
print(student)

[[83 73 77 78]
 [68 64 67 75]
 [62 63 73 75]
 [73 63 72 76]
 [69 65 64 70]
 [65 63 61 72]]


In [22]:
Avg2= np.mean(student, axis = 1)  #avg all
print(Avg2)

[77.75 68.5  68.25 71.   67.   65.25]


In [23]:
print(np.array_equal(Avg1,Avg2))

False


# list to numpy_arr

In [25]:
a= [23,34,56,78,22]
b= [24,34,52,78,22]

In [56]:
x = np.array([23,34,56,78,22])
y = np.array([24,34,52,78,22])

In [57]:
if (a==b):
    print("Same list")
else:
    print("Not Same list")

Not Same list


In [64]:
#for arr
same = x & y
if np.all(same) == True:
    print("Same list")
else:
    print("Not Same list")


Same list


# try out 18 sir sln

In [33]:
marks = np.array([[75,80,85],
                [80,85,90],
                [90,95,75]])
marks

array([[75, 80, 85],
       [80, 85, 90],
       [90, 95, 75]])

In [34]:
marks_mean = np.mean(marks, axis=1)
print(marks_mean)

[80.         85.         86.66666667]


In [35]:
marks[1] +=5

marks

array([[75, 80, 85],
       [85, 90, 95],
       [90, 95, 75]])

In [36]:
marks_mean = np.mean(marks, axis=1)
print(marks_mean)

[80.         90.         86.66666667]


# Comparison Masking , Bool logic

In [43]:
x = np.array([1,2,3,4,5])
print(x>=3)

[False False  True  True  True]


In [44]:
temp = np.where(x>=3)
temp

(array([2, 3, 4], dtype=int64),)

In [53]:
y = np.array([1,2,3,7,5]) 
temp = np.any(x==y)      #if one is true/same
print(temp)

True


In [62]:
temp = np.all(x==y)   #if all is true/same
print(temp)

False
