# Understanding Data Types in python

In [2]:
for i in range(0,10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [4]:
L=list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [13]:
type(L)

list

In [14]:
type(L[0])

int

In [10]:
L2=[str(i) for i in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [15]:
type(L2[1])

str

In [16]:
L3=[True, "2", 3.0, 4]
L3

[True, '2', 3.0, 4]

In [19]:
print([type(i) for i in L3])

[<class 'bool'>, <class 'str'>, <class 'float'>, <class 'int'>]


# Fixed type Array

In [27]:
import array
L = list(range(10))
#L= ["a","b",True, 4]
A = array.array('i',L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
import numpy as np

In [34]:
A = np.array([1,3,6,2,8])
A

array([1, 3, 6, 2, 8])

In [36]:
A = np.array([1.5,3,6,2,8], dtype=np.float32)
print(A)

[1.5 3.  6.  2.  8. ]


# Creating Arrays from Python List

### nested list result for multidimentional appay

In [39]:
A=np.array([range(i,i+4) for i in [3,4,5,6]])
A

array([[3, 4, 5, 6],
       [4, 5, 6, 7],
       [5, 6, 7, 8],
       [6, 7, 8, 9]])

# array initialized with zero

In [41]:
A = np.zeros(10, dtype=int)
A

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# array initialized with one

In [44]:
A = np.ones(10, dtype=int)
A

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [45]:
A = np.ones((3,5), dtype=int)
A

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [46]:
A = np.ones((3,5), dtype=float)
A

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# array initialized with 3.55

In [49]:
A = np.full((3,5), 3.55)
A

array([[3.55, 3.55, 3.55, 3.55, 3.55],
       [3.55, 3.55, 3.55, 3.55, 3.55],
       [3.55, 3.55, 3.55, 3.55, 3.55]])

In [50]:
A = np.full((3,5), "444")
A

array([['444', '444', '444', '444', '444'],
       ['444', '444', '444', '444', '444'],
       ['444', '444', '444', '444', '444']], dtype='<U3')

#  array initialized with a linear siquence

In [52]:
A = np.arange(2,20,2)
A

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [53]:
A = np.arange(2,20,2.5)
A

array([ 2. ,  4.5,  7. ,  9.5, 12. , 14.5, 17. , 19.5])

#  array initialized with evenly space maintained value 

In [57]:
A = np.linspace(2,20,7)
A

array([ 2.,  5.,  8., 11., 14., 17., 20.])

In [58]:
A = np.linspace(0,10,6)
A

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [59]:
A = np.linspace(0,10,5)
A

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

# array initialized with random variable

In [64]:
A = np.random.randint(0,10, (3,3))
A

array([[2, 0, 7],
       [0, 8, 9],
       [3, 8, 5]])

In [67]:
A = np.random.random((3,4))
A

array([[0.89615481, 0.14165103, 0.68816658, 0.94661776],
       [0.48504801, 0.02172126, 0.18042084, 0.55398331],
       [0.78125139, 0.67032124, 0.20224797, 0.10237241]])

In [68]:
A = np.random.normal(0,10, (3,3))
A

array([[-7.99851184, -9.59110668, 10.02461475],
       [12.65036911, -1.55100684, -0.96216458],
       [-9.15978366,  2.09612613, -5.24346066]])

# Create a 3*3 identity matrix

In [70]:
A = np.eye(4)
A

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [73]:
# empty array of 4 size

In [74]:
A = np.empty(4)
A

array([1., 1., 1., 1.])

# numpy array attributes

In [6]:
import numpy as np

np.random.seed(0)

x1=np.random.randint(10, size=6)
x2=np.random.randint(10, size=(3,4))
x3=np.random.randint(10, size=(3,4,5))

In [74]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [8]:
print("x1 : ",x1)
print("x1 : ",x2)
print("x1 : ",x3)

x1 :  [5 0 3 3 7 9]
x1 :  [[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
x1 :  [[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


In [9]:
print("x3 ndim : ",x3.ndim)
print("x3 shape : ",x3.shape)
print("x3 size : ",x3.size)

x3 ndim :  3
x3 shape :  (3, 4, 5)
x3 size :  60


In [46]:
print("x3 dtype : ",x3.dtype)

x3 dtype :  int32


# get array index

In [47]:
x1[3]

3

In [48]:
x2[2,-1]

7

# array slicing

In [17]:
x1

array([5, 0, 3, 3, 7, 9])

In [16]:
x1[::2]

array([5, 3, 7])

In [18]:
x1[:5]

array([5, 0, 3, 3, 7])

In [20]:
x1[1::2]

array([0, 3, 9])

In [21]:
# reverse array

In [22]:
x1[::-1]

array([9, 7, 3, 3, 0, 5])

In [23]:
x1[3::-2]

array([3, 0])

# For multidimention array slicing

In [32]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [33]:
x2[:2,:3]

array([[3, 5, 2],
       [7, 6, 8]])

In [34]:
x2[:3, ::2]

array([[3, 2],
       [7, 8],
       [1, 7]])

In [35]:
x2[:, ::2]

array([[3, 2],
       [7, 8],
       [1, 7]])

# reverse multidimention array

In [42]:
x2[::-1, ::-1]

array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 3]])

In [43]:
x2[:,0] # first column of x2

array([3, 7, 1])

In [44]:
x2[0,:] # first row of x2

array([3, 5, 2, 4])

#  Copy views

In [72]:
x2=np.array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [73]:
subx2 = x2[:2,:2]
subx2

array([[3, 5],
       [7, 6]])

In [65]:
subx2[0,0] = 999
subx2

array([[999,   5],
       [  7,   6]])

In [66]:
x2  # change main array

array([[999,   5,   2,   4],
       [  7,   6,   8,   8],
       [  1,   6,   7,   7]])

### copy sub array

In [68]:
subx2 = x2[:2,:2].copy()
subx2

array([[999,   5],
       [  7,   6]])

In [70]:
subx2[0,0] = 9999999
subx2

array([[9999999,       5],
       [      7,       6]])

In [71]:
x2

array([[999,   5,   2,   4],
       [  7,   6,   8,   8],
       [  1,   6,   7,   7]])

# create array

In [76]:
L1=[2,2,2,2,2,2,2]
L2=[3,3,3,3,3,3,3]
L3=[2,3,4,5,6,8,9]
Arr = np.array([L1,L2,L3])

print(Arr)

[[2 2 2 2 2 2 2]
 [3 3 3 3 3 3 3]
 [2 3 4 5 6 8 9]]
